In [1]:
import math
import torch
import pandas as pd
import numpy as np
from utils import toTorchTensers, NormalizeData
from Models import ForcastModel

data_url = r'./data/New_Feats_12-04_12-09-09.xlsx'
data_egypt = pd.read_excel(data_url)

In [2]:
# data
DATA = data_egypt
DATA = NormalizeData(DATA)
DATA = DATA.to_numpy()
DATA = DATA[:, 1:]
print(DATA)

np.random.seed(1)
np.random.shuffle(DATA)
split_point = math.floor(len(DATA) * 0.75)

train_x, train_y = DATA[:split_point, 1:], DATA[:split_point, 0:1]
test_x, test_y = DATA[split_point:, 1:], DATA[split_point:, 0:1]

[train_x, train_y, test_x, test_y] = toTorchTensers(
  train_x, train_y, test_x, test_y
)

[[0.         0.78375769 0.82975703 0.65604067]
 [0.         0.46389538 0.12236483 0.42620859]
 [0.         0.24049922 0.71626908 0.4170197 ]
 ...
 [1.         0.48928325 0.36004919 0.45143803]
 [1.         0.3293826  0.42042672 0.70597426]
 [1.         0.74629243 0.43832318 0.60340073]]


In [5]:
# training
model = ForcastModel(input=3)
model.fit(train_x, train_y, epoches=50)

epoche: 0, loss: 0.22738655, execution time: 1.4s
epoche: 1, loss: 0.22199683, execution time: 1.3s
epoche: 2, loss: 0.22363076, execution time: 1.5s
epoche: 3, loss: 0.22397846, execution time: 1.4s
epoche: 4, loss: 0.22419631, execution time: 1.4s
epoche: 5, loss: 0.22446391, execution time: 1.4s
epoche: 6, loss: 0.22467363, execution time: 1.5s
epoche: 7, loss: 0.22486265, execution time: 1.7s
epoche: 8, loss: 0.22501217, execution time: 1.6s
epoche: 9, loss: 0.22514610, execution time: 1.4s
epoche: 10, loss: 0.22527115, execution time: 1.4s
epoche: 11, loss: 0.22536646, execution time: 1.5s
epoche: 12, loss: 0.22457764, execution time: 1.5s
epoche: 13, loss: 0.22535191, execution time: 1.5s
epoche: 14, loss: 0.22559117, execution time: 1.5s
epoche: 15, loss: 0.22570278, execution time: 1.5s
epoche: 16, loss: 0.22575822, execution time: 1.5s
epoche: 17, loss: 0.22577995, execution time: 1.6s
epoche: 18, loss: 0.22578779, execution time: 1.5s
epoche: 19, loss: 0.22580099, execution t

In [6]:
# testing
model.test(test_x, test_y, bar=0.7)

loss: 0.2259, acc: 0.4550
