In [91]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import metrics
import math
import pandas as pd
import numpy as np

In [92]:
# data
DATA = np.genfromtxt(r'./data/Data_egypt_cluster.csv', delimiter=',')

train_x, test_x, train_y, test_y = train_test_split(
    DATA[:, 1:], DATA[:, 0], test_size=0.25, random_state=1
)

print(train_x.shape, train_y.shape)
print(
    f'class 1: {(train_y == 1).sum()}',
    f'class 2: {(train_y == 2).sum()}',
    f'class 3: {(train_y == 3).sum()}',
    f'class 4: {(train_y == 4).sum()}',
)


(664, 12) (664,)
class 1: 75 class 2: 262 class 3: 264 class 4: 63


In [93]:
tree_classifier = tree.DecisionTreeClassifier()
tree_classifier.fit(train_x, train_y)

DecisionTreeClassifier()

In [94]:
pred_y = tree_classifier.predict(test_x)

print("ACC:", metrics.accuracy_score(test_y, pred_y))
print("RMSE:", metrics.mean_squared_error(test_y, pred_y))
print(metrics.confusion_matrix(test_y, pred_y))


ACC: 0.9099099099099099
RMSE: 0.23423423423423423
[[29  2  0  1]
 [ 3 73  3  0]
 [ 0  8 75  0]
 [ 3  0  0 25]]
