In [10]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import metrics
import math
import pandas as pd
import numpy as np

In [11]:
# data
DATA = np.genfromtxt(
    r'./data/other_banknote_authentication_c.csv', delimiter=','
)

train_x, test_x, train_y, test_y = train_test_split(
    DATA[:, :-1], DATA[:, -1], test_size=0.25, random_state=1
)

print(train_x.shape, train_y.shape)
print(
    f'class 1: {(train_y == 1).sum()}',
    f'class 2: {(train_y == 2).sum()}',
    f'class 3: {(train_y == 3).sum()}',
    f'class 4: {(train_y == 4).sum()}',
)


(1029, 4) (1029,)
class 1: 361 class 2: 208 class 3: 236 class 4: 224


In [18]:
tree_classifier = tree.DecisionTreeClassifier()
tree_classifier.fit(train_x, train_y)

DecisionTreeClassifier()

In [19]:
pred_y = tree_classifier.predict(test_x)

print("ACC:", metrics.accuracy_score(test_y, pred_y))
print("RMSE:", metrics.mean_squared_error(test_y, pred_y))
print(metrics.confusion_matrix(test_y, pred_y))


ACC: 0.9941690962099126
RMSE: 0.014577259475218658
[[131   0   1   0]
 [  0  61   0   0]
 [  0   0  74   1]
 [  0   0   0  75]]
